// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oauiwqhlwoefihkymiic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdWl3cWhsd29lZmloa3ltaWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjkwNTEsImV4cCI6MjA3MDk0NTA1MX0.3SxJGR0OevCAN0RFS8rGOznj4o26IpBURhGdJQNj7A4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});